"""Initial migration

Revision ID: 60369ff0f184
Revises: 
Create Date: 2025-05-16 15:26:58.889294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60369ff0f184'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_device_id'), 'sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_device_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
